### ISSUE TITLE
Is it possible to debug clang build?

### ISSUE THREAD

**Issue by OleksandrKvl** [microsoft/vscode-cmake-tools#1203]
Hi, sorry if this is duplication, I tried to read similar issues but still can't get it. 
I used gcc kit, build/debug worked perfectly. Now I'm using Clang 10 kit, build is OK but I can't debug it.
First attempt was without any changes to project, log:
```
[proc] Executing command: /usr/bin/lldb-mi-10 --version
[proc] Executing command: /usr/bin/gdb-10 --version  <--- gdb-10 o_0 ??
[proc] Executing command: /usr/bin/lldb-10 --version
[proc] Executing command: /usr/bin/lldb-10 --version
```
And then it hangs with output:
```
warning: ignoring unknown option: --interpreter=mi
warning: ignoring unknown option: --tty=/dev/pts/2
```
I guessed that lldb is not supported at atll and I tried to use "cmake.debugConfig": {"miDebuggerPath": "/usr/bin/gdb"  and it didn't work.
1. Is it ever possible to use lldb out of the box?
2. Is it possible to build with clang and debug with gdb?

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.16
- **VSCode Version**: 1.44.2
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Clang 10

**Comment by andreeis** [comment]
We fixed this issue with https://github.com/microsoft/vscode-cmake-tools/commit/70e935ba8acf5fcf16f1f46dc497a943e231dd22.

**Comment by bobbrow** [comment]
Duplicate of #1060

**Comment by Phi-Li** [comment]
I am on version 1.4.1 and can still reproduce this with lldb 10.
I tried to set:
```
"cmake.debugConfig": {
    "MIMode": "lldb",
    "miDebuggerPath": "/usr/bin/lldb-10"
}
```
then come the error:
```
[debugger] Unable to automatically determine debugger corresponding to compiler: /bin/clang++-10
[main] Failed to generate debugger configuration
```

**Comment by WenyinWei** [comment]
The same problem as @OleksandrKvl with CMake Tools version 1.7.3 on Ubuntu 20.04, I guess the problem lies at that lldb simply doesn't have these two options `--interpreter` and `--tty`. It is probably a nontrivial work to let lldb export debug infomation through a TTY.

```
OVERVIEW: LLDB

USAGE: lldb-13 [options]

ATTACHING:
  --attach-name <name> Tells the debugger to attach to a process with the given name.
  --attach-pid <pid>   Tells the debugger to attach to a process with the given pid.
  -n <value>           Alias for --attach-name
  -p <value>           Alias for --attach-pid
  --wait-for           Tells the debugger to wait for a process with the given pid or name to launch before attaching.
  -w                   Alias for --wait-for

COMMANDS:
  --batch              Tells the debugger to run the commands from -s, -S, -o & -O, and then quit.
  -b                   Alias for --batch
  -K <value>           Alias for --source-on-crash
  -k <value>           Alias for --one-line-on-crash
  --local-lldbinit     Allow the debugger to parse the .lldbinit files in the current working directory, unless --no-lldbinit is passed.
  --no-lldbinit        Do not automatically parse any '.lldbinit' files.
  --one-line-before-file <command>
                       Tells the debugger to execute this one-line lldb command before any file provided on the command line has been loaded.
  --one-line-on-crash <command>
                       When in batch mode, tells the debugger to run this one-line lldb command if the target crashes.
  --one-line <command> Tells the debugger to execute this one-line lldb command after any file provided on the command line has been loaded.
  -O <value>           Alias for --one-line-before-file
  -o <value>           Alias for --one-line
  -Q                   Alias for --source-quietly
  --source-before-file <file>
                       Tells the debugger to read in and execute the lldb commands in the given file, before any file has been loaded.
  --source-on-crash <file>
                       When in batch mode, tells the debugger to source this file of lldb commands if the target crashes.
  --source-quietly     Tells the debugger to execute this one-line lldb command before any file has been loaded.
  --source <file>      Tells the debugger to read in and execute the lldb commands in the given file, after any file has been loaded.
  -S <value>           Alias for --source-before-file
  -s <value>           Alias for --source
  -x                   Alias for --no-lldbinit

OPTIONS:
  --arch <architecture>  Tells the debugger to use the specified architecture when starting and running the program.
  -a <value>             Alias for --arch
  --capture-path <filename>
                         Tells the debugger to use the given filename for the reproducer.
  --capture              Tells the debugger to capture a reproducer.
  --core <filename>      Tells the debugger to use the full path to <filename> as the core file.
  -c <value>             Alias for --core
  --debug                Tells the debugger to print out extra information for debugging itself.
  -d                     Alias for --debug
  --editor               Tells the debugger to open source files using the host's "external editor" mechanism.
  -e                     Alias for --editor
  --file <filename>      Tells the debugger to use the file <filename> as the program to be debugged.
  -f <value>             Alias for --file
  --help                 Prints out the usage information for the LLDB debugger.
  -h                     Alias for --help
  --no-use-colors        Do not use colors.
  --replay <filename>    Tells the debugger to replay a reproducer from <filename>.
  --reproducer-generate-on-exit
                         Generate reproducer on exit.
  --reproducer-no-generate-on-signal
                         Don't generate reproducer when a signal is received.
  --reproducer-no-verify Disable the reproducer verification.
  --reproducer-no-version-check
                         Disable the reproducer version check.
  --version              Prints out the current version number of the LLDB debugger.
  -v                     Alias for --version
  -X                     Alias for --no-use-color

REPL:
  -r=<flags>     Alias for --repl=<flags>
  --repl-language <language>
                 Chooses the language for the REPL.
  --repl=<flags> Runs lldb in REPL mode with a stub process with the given flags.
  --repl         Runs lldb in REPL mode with a stub process.
  -R <value>     Alias for --repl-language
  -r             Alias for --repl

SCRIPTING:
  -l <value>    Alias for --script-language
  --python-path Prints out the path to the lldb.py file for this version of lldb.
  -P            Alias for --python-path
  --script-language <language>
                Tells the debugger to use the specified scripting language for user-defined scripts.

EXAMPLES:
  The debugger can be started in several modes.

  Passing an executable as a positional argument prepares lldb to debug the
  given executable. To disambiguate between arguments passed to lldb and
  arguments passed to the debugged executable, arguments starting with a - must
  be passed after --.

    lldb --arch x86_64 /path/to/program program argument -- --arch armv7

  For convenience, passing the executable after -- is also supported.

    lldb --arch x86_64 -- /path/to/program program argument --arch armv7

  Passing one of the attach options causes lldb to immediately attach to the
  given process.

    lldb -p <pid>
    lldb -n <process-name>

  Passing --repl starts lldb in REPL mode.

    lldb -r

  Passing --core causes lldb to debug the core file.

    lldb -c /path/to/core

  Command options can be combined with these modes and cause lldb to run the
  specified commands before or after events, like loading the file or crashing,
  in the order provided on the command line.

    lldb -O 'settings set stop-disassembly-count 20' -o 'run' -o 'bt'
    lldb -S /source/before/file -s /source/after/file
    lldb -K /source/before/crash -k /source/after/crash

  Note: In REPL mode no file is loaded, so commands specified to run after
  loading the file (via -o or -s) will be ignored.
```

**Comment by erwincoumans** [comment]
Same issue, ubuntu latest version of Visual Studio Code and CMake, using clang++-13 then lldb debugging reports the error:
```
error: unknown option: --interpreter=mi
error: unknown option: --tty=/dev/pts/7
```
Is there some file to edit, to avoid passing those values (note there is no launch.json file)

**Comment by bobbrow** [comment]
The lldb debug support goes through the C++ extension.  We made it possible to select your own debugger via the `cmake.debugConfig` setting, but the errors you're seeing now come from the C++ extension, so it would be better to open an issue there and see what other configuration steps you might be missing.  I believe these errors mean that you are using the mainline lldb to debug and you need to get a copy of lldb-mi (which I believe the C++ extension bundles).

**Comment by erwincoumans** [comment]
It looks like we need to install lldb-mi
```
sudo apt-get install liblldb-13-dev
git clone https://github.com/lldb-tools/lldb-mi
cd lldb-mi
cmake .
cmake --build .
sudo make install
```
then before running code, make sure this environment variable is set
```
export LLDB_DEBUGSERVER_PATH=/usr/bin/lldb-server-13
```

Then it worked for me.
