### ISSUE TITLE
[1.4.0-beta] VS environment not set correctly

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1243]
@andreeis Now it initializes a correct cross-compiler for MSVC CMake generator, but there is an issue. 

If you have `"cmake.preferredGenerators": ["Ninja"],` in global settings - CMake-Tools'll never initialize `vcvarsall.bat`. It's a bit unexpected. Shouldn't it initialize a correct environment anyway if both `visualStudio` and `visualStudioArchitecture` are present as per documentation?

_Originally posted by @Minimonium in https://github.com/microsoft/vscode-cmake-tools/issues/1084#issuecomment-629515919_

**Comment by bobbrow** [comment]
Confirmed.  We'll fix this before releasing 1.4.0
```
varsForVSInstallation path:'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise' version:16.5.30011.22 host arch:x86 - target arch:undefined
main.js:60823
Error running C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86_undefined, can not found INCLUDE
```

**Comment by lygstate** [comment]
same issue
```
[main] 正在配置文件夹: aeron 
[driver] 删除 e:/CI-Cor-Ready/xemu-rpc/aeron/build-cmake/RelWithDebInfo/CMakeCache.txt
[driver] 删除 e:\CI-Cor-Ready\xemu-rpc\aeron\build-cmake\RelWithDebInfo\CMakeFiles
[proc] 执行命令: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -He:/CI-Cor-Ready/xemu-rpc/aeron -Be:/CI-Cor-Ready/xemu-rpc/aeron/build-cmake/RelWithDebInfo -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is unknown
[cmake] -- The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:51 (project):
[cmake]   No CMAKE_C_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
[cmake]   the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:51 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "E:/CI-Cor-Ready/xemu-rpc/aeron/build-cmake/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
[cmake] See also "E:/CI-Cor-Ready/xemu-rpc/aeron/build-cmake/RelWithDebInfo/CMakeFiles/CMakeError.log".

```

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.

**Comment by AndWass** [comment]
I am still having this issue with 1.4.0, downgrading to 1.3.1 fixes it.

**Comment by HenryAWE** [comment]
Still having the same issue, launching VS Code from VS command prompt fixes it

**Comment by andreeis** [comment]
You shouldn't need to launch from the VS command prompt, but it's good that's a temporary workaround.
You can also try to delete the build folder and reopen your project. This fixed the configure process for all the users that upgraded to 1.4.0.
There is a migration incompatibility that we're fixing now for 1.4.1 but in the mean time I hope the above will unblock you.

**Comment by benvanik** [comment]
I'm also having issues with 1.4.0 of the `fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory` kind, which is new. Downgrading to 1.3.1 works. A coworker had the same issue.

**Comment by andreeis** [comment]
@benvanik, please let me know the following: what kit you are using (which VS exactly, which host-target platforms), do you set any generator explicitly in settings. Please share the contents of your kits file right after migration (only the VS section is fine, no need to include anything else).

Then, are you able to get unblocked with using 1.4.0 after deleting the build folder, reload project and rescanning kits? Do this after you paste us the kits content.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.4.1 which was published today.
Let us know if you encounter any issues with this release.
