### ISSUE TITLE
CMake Panel cannot open Files outside the currently open Folder

### ISSUE THREAD

**Issue by YmiYugy** [microsoft/vscode-cmake-tools#1254]
### Brief Issue Summary
Consider the following file structure
root
├── main
│   └── CMakeLists.txt
└── main.cpp

When I open the main folder in VSCode the projects configures and builds successfully, but when I try to open main.cpp from the project outline I get a the following error:
`Unable to open 'main.cpp': Unable to read file 'path/to/root/main/path/to/root/main.cpp' (Error: Unable to resolve non-existing file 'path/to/root/main/path/to/root/main.cpp').`

### Platform and Versions

- **Operating System**:macOS 
- **CMake Version**:3.17.2 
- **VSCode Version**:1.45.1 
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Clang 11

**Comment by BlurryLight** [comment]
Similar problem.
![截图_2020-05-29_10-03-35](https://user-images.githubusercontent.com/14940338/83213044-b8bed500-a193-11ea-8211-bf4187c97e67.png)

**Comment by bobbrow** [comment]
@YmiYugy your issue should be fixed in version 1.4.0. Can you update the extension and try again?
@BlurryLight your issue was the problem matcher issue you created an issue for #1270 

Thank you!

**Comment by mutoo** [comment]
hi @bobbrow, I am using 1.4.2 CMake Tools on macOS, but the issue is still there:
```
Unable to open 'main.cpp': Unable to read file '/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp' (Error: Unable to resolve non-existing file '/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp').
```

The project structure looks like: 
```
A $ tree -L 2 .
.
├── README.md
├── console
│   ├── build
│   └── CMakeLists.txt
├── src
│   └── main.cpp
└── third-party
```

with this simple setup:

```
set(MAIN_SOURCE_DIR "../src")

file(GLOB_RECURSE CPP_HEADERS ${MAIN_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE CPP_SOURCES ${MAIN_SOURCE_DIR}/*.cpp)

add_executable(
    A
    ${CPP_HEADERS}
    ${CPP_SOURCES}
)
```

As you can see, the error reports a path with `<CMakeLists Dir>+<Absolute Source Path>`, which is duplicate and totally wrong.
```
'/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp'
```

**Platform and Versions**
Operating System:macOS
CMake Version:3.18.4
VSCode Version:1.50.1
CMake Tools Extension Version: 1.4.2
Compiler/Toolchain: Clang 11

**Comment by bobbrow** [comment]
@mutoo I created a new issue for this.
