### ISSUE TITLE
CMake Cache UI doesn't save variables in some cases

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1848]
empty string cache variable --> edit some value in cache UI --> SAVE (this triggers configure accordingly) --> but CMakeCache.txt does not have the new value and a reload of the UI will lose the text.

Same scenario works fine when changing from value1 to value2, or from value to empty.
Broken for changing from empty to value.

**Comment by noodlecollie** [comment]
I can also confirm that this is happening to me, on version 1.9.2. Good to know that it only occurs when changing a variable from empty to non-empty, so I can work around it for now.

**Comment by gcampbell-msft** [comment]
@andreeis @noodlecollie We believe this has been fixed since the last activity on this bug. Due to that, we will close this issue. Please let us know if this is not the case and we can re-open and investigate. Thanks!

**Comment by noodlecollie** [comment]
This issue is not fixed for me in v1.14.34. Should I be waiting for v1.15 to be available?

**Comment by noodlecollie** [comment]
This issue is still not fixed for me in v1.16.32.

**Comment by gcampbell-msft** [comment]
@noodlecollie Thank you for calling this out. I will re-open and label it as a bug and put it in our backlog.
