### ISSUE TITLE
Presets are not reloaded when an included file is changed until reloading the whole project

### ISSUE THREAD

**Issue by Hugal31** [microsoft/vscode-cmake-tools#3963]
### Brief Issue Summary

When adding an include directive in a CMake preset, any change made to the included files won't trigger a reload of the presets. Any further CMake configure will not take in account the changes, until the CMake(User)Presets.json is modified or VSCode is restarted.

If VSCode is restarted, then the included file seems to be added to the watches and it works as expected.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.91.1",
  "cmtVersion": "1.18.44",
  "configurations": [
    {
      "folder": "/tmp/testcode",
      "cmakeVersion": "3.29.6",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {
        "C": "/usr/bin/cc",
        "CXX": "/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [
      ""
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

To reproduce:
Create a preset-based project
In the CMakeLists.txt, display a cache or env variable.
Use the "include" directive in the preset and in the main CMakePresets.txt, inherit from a configurePreset.
Change the varaible in the included preset file.

E.g.
```cmake
# CMakeLists.txt
message("THE_VAR is $ENV{THE_VAR}")
message("THE_OTHER_VAR is ${THE_OTHER_VAR}")
```

CMakePresets.json:
```json
{
    "version": 4,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 23
    },
    "include": ["presets.json" ],
    "configurePresets": [
        {
            "name": "Debug",
            "inherits": "base"
        }
    ]
}
```

presets.json
```json
{
    "version": 4,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 23
    },
    "configurePresets": [
        {
            "name": "base",
            "cacheVariables": {
                "THE_OTHER_VAR": "2"
            },
            "environment": {
                "THE_VAR": "2"
            }
        }
    ]
}
```

Then try to change the variables in presets.json and reconfigure. The changes are not taken in account.
Restart VSCode and it works fine.

**Comment by gcampbell-msft** [comment]
@Hugal31 I believe this should be fixed in the most recent pre-release, could you try the most recent pre-release version?

**Comment by v-frankwang** [comment]
@gcampbell-msft @Hugal31 I verified on the latest pre-release version and the issue has been fixed.

ENV:
CMake Tools：v1.19.37(pre-release)
vscode：v1.92.0
C/C++:v1.21.6

Actual result:
![3963](https://github.com/user-attachments/assets/4be0849c-776f-4eae-bc70-cb4135a8dac3)

**Comment by Hugal31** [comment]
I still have the issue using
* CMake Tools v1.19.37 (pre-release)
* VS code 1.92.0
* C/C++ v1.21.6

Another way to reproduce is
1. From a working setup, rename the included presets.json and change the "include" directive to make it work.
2. Configure: the variables are good.
3. Change a variable in the renamed presets.json: the preset is not reloaded.
4. Configure: the variables are not changed.

**Comment by v-frankwang** [comment]
@Hugal31 Thank you very much for your reply! Would you be able to provide some screenshots or recordings so we can look into the issue?

**Comment by Hugal31** [comment]
Sure,

Here is a video and the minimal project. I tried with vscode 1.92.1

https://github.com/user-attachments/assets/ce9220f2-58e6-410f-a9b5-41dc4f22513
[testcmaketools.tar.gz](https://github.com/user-attachments/files/16558185/testcmaketools.tar.gz)

**Comment by v-frankwang** [comment]
@Hugal31 @moyo1997 We reproduced the problem using the project provided by the customer, after changing the filename of presets.json and the values of **THE_OTHER_VAR** and **THE_VAR** in the project, we ran the command **CMake:Delete cache and reconfigure**, the variables are not changed. If you resave the CMakePresets.json file after the variables are good.

ENV：

- CMake Tools v1.19.38 (pre-release)
- VS code 1.92.1
- C/C++ v1.21.6

Actual result:
![3963](https://github.com/user-attachments/assets/3b384fe5-944c-4c0a-9d3e-8917e059ac18)

**Comment by qarni** [comment]
@Hugal31 I believe this is fixed in the latest pre-release!

**Comment by Hugal31** [comment]
I still have it with v1.20.3 (pre-release) on VScode 1.92.2 :/

**Comment by gcampbell-msft** [comment]
@Hugal31 @v-frankwang Could it be due to the fact that your file is named `CMakepresets.json` rather than `CMakePresets.json`? 

@v-frankwang Could you test? Thanks. If not, please create a new issue with the details necessary for us to investigate. Thanks!

**Comment by Hugal31** [comment]
> @Hugal31 @v-frankwang Could it be due to the fact that your file is named `CMakepresets.json` rather than `CMakePresets.json`?

I don't know why that was the case, but in the .tar.gz I provided it's really CMakePresets.json and the bug is present.

**Comment by gcampbell-msft** [comment]
@Hugal31 Ah, re-reading your most recent repro steps, I think that the issue is due to the fact that we only create listeners for the files on startup. If you rename and save, in the current implementation, a reload will be needed. I'll reopen this and put it on our backlog.

**Comment by Amy-Li03** [comment]
Verified this issue on the CMake Tools latest version: v1.20.27 (pre-release), it has been fixed. After renaming the included presets.json and changing a variable in the renamed presets.json which is not reloaded, the variables are good.

![Image](https://github.com/user-attachments/assets/03a387c8-17f7-4a63-b6a0-3480c95e87e5)
