### ISSUE TITLE
[Loc]"CMake: debug" command not localized

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-cmake-tools#4235]
### Brief Issue Summary

**More info:**
1. This issue is reproduced on Linux and Windows, Mac platforms
2. Repro Language: **ITA**
3. Not repro language: CHT, JPN, KOR, ESN, FRA, PLK, DEU, RUS, CSY, CHS, PTB, TRK

**Repro steps:**
1. Open this folder [CMakeProject1.zip](https://github.com/user-attachments/files/18407009/CMakeProject1.zip) by VSCode
2. Change the language to ITA
3. Click F1 and run command "CMake: debug"

Actual result:
The command "CMake: debug" is not localized

**ITA:**
![Image](https://github.com/user-attachments/assets/9ae8424e-07d0-401d-b28b-b5b3bed74169)

Expect result:
Command “CMake: debug” has been localized
**CHS:** 
![Image](https://github.com/user-attachments/assets/6fcf3a92-07e2-4b88-a106-13582243e1e7)

**Comment by gcampbell-msft** [comment]
I've created a loc bug

**Comment by Yingzi1234** [comment]
@gcampbell-msft We verified this issue on latest version 1.20.48(pre-release) it is still reproduced, you can get the details below. Thank you!
![Image](https://github.com/user-attachments/assets/0236a827-3760-47b1-88e3-bec7a302660d)

**Comment by gcampbell-msft** [comment]
This is fixed: 

![Image](https://github.com/user-attachments/assets/eb591b8d-c834-4f60-82bb-df8b9fad2f08)

**Comment by Yingzi1234** [comment]
@gcampbell-msft This issue only reproduced on ITA language, we found that you verified on ESN and we verified on latest CMake Tools version 1.20.49(pre-release), it is still not fixed.
**ITA:**
![Image](https://github.com/user-attachments/assets/7db6ddfe-f9f6-4094-858c-97bd58d51145)

**Comment by gcampbell-msft** [comment]
I've confirmed with loc team that it is because the words are the same in italian. Closing.
