### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'major')

### ISSUE THREAD

**Issue by lordrebel** [microsoft/vscode-cmake-tools#4474]
### Brief Issue Summary

today when i try to build my project
 i got:
"Cannot read properties of undefined (reading 'major')"

my vscode settings:
```json
{
    "files.associations": {
        "*.inc": "cpp",
        "*.txt": "makefile",
        "*.go": "go",
        "*.def": "cpp",
        "functional": "cpp",
        "memory": "cpp",
        "optional": "cpp",
        "sstream": "cpp",
        "type_traits": "cpp",
        "*.tcc": "cpp",
        "bitset": "cpp",
        "deque": "cpp",
        "forward_list": "cpp",
        "list": "cpp",
        "string": "cpp",
        "vector": "cpp",
        "streambuf": "cpp",
        "system_error": "cpp",
        "array": "cpp",
        "future": "cpp",
        "istream": "cpp",
        "ostream": "cpp",
        "typeinfo": "cpp",
        "atomic": "cpp",
        "bit": "cpp",
        "cctype": "cpp",
        "chrono": "cpp",
        "cinttypes": "cpp",
        "clocale": "cpp",
        "cmath": "cpp",
        "complex": "cpp",
        "condition_variable": "cpp",
        "cstdarg": "cpp",
        "cstddef": "cpp",
        "cstdint": "cpp",
        "cstdio": "cpp",
        "cstdlib": "cpp",
        "cstring": "cpp",
        "ctime": "cpp",
        "cwchar": "cpp",
        "cwctype": "cpp",
        "map": "cpp",
        "set": "cpp",
        "unordered_map": "cpp",
        "unordered_set": "cpp",
        "exception": "cpp",
        "algorithm": "cpp",
        "iterator": "cpp",
        "memory_resource": "cpp",
        "numeric": "cpp",
        "random": "cpp",
        "ratio": "cpp",
        "regex": "cpp",
        "string_view": "cpp",
        "tuple": "cpp",
        "utility": "cpp",
        "fstream": "cpp",
        "initializer_list": "cpp",
        "iomanip": "cpp",
        "iosfwd": "cpp",
        "iostream": "cpp",
        "limits": "cpp",
        "mutex": "cpp",
        "new": "cpp",
        "shared_mutex": "cpp",
        "stdexcept": "cpp",
        "thread": "cpp",
        "variant": "cpp",
        "strstream": "cpp",
        "cfenv": "cpp",
        "typeindex": "cpp",
        "valarray": "cpp",
        "codecvt": "cpp",
        "filesystem": "cpp",
        "compare": "cpp",
        "concepts": "cpp",
        "numbers": "cpp",
        "semaphore": "cpp",
        "span": "cpp",
        "stop_token": "cpp"
    },
    // "cmake.generator": "Ninja",
    // "cmake.buildArgs": [
    //     "-j 16"
    // ],
    // "cmake.cmakePath": "cmake",
    // "cmake.configureOnOpen": false,
    // "cmake.configureSettings": {
    //     // "CMAKE_C_COMPILER": "clang",
    //     // "CMAKE_CXX_COMPILER": "clang++",
    //     //"TBC_USE_LLD": "ON",
    //     "CMAKE_INSTALL_PREFIX": "${workspaceFolder}/install"
    // },
    "C_Cpp.intelliSenseEngine": "Disabled",
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "editor.tabSize": 2,
    "C_Cpp.formatting": "clangFormat",
    "C_Cpp.clang_format_style": "LLVM",
    "python.analysis.extraPaths": [
        "${workspaceFolder}/../llvm_release/src/python",
        "${workspaceFolder}/../llvm_release/src/python/MLIRPythonSources.Core/_mlir_libs",
        "install/python"
    ],
    "[python]": {
        "editor.defaultFormatter": "eeyore.yapf",
    },
    "editor.formatOnSave": true,
    "yapf.args": [
        "--style={based_on_style:pep8, indent_width:4, column_limit:100}"
    ],
    "python": {
        "tabSize": 4
    },
    "restructuredtext.preview.name": "docutils",
    "esbonio.sphinx.confDir": ".",
    //"clangd.path": "clangd",
    "clangd.arguments": [
        "--background-index",
        "--compile-commands-dir=./build", //compile_command.json相对路径，cmake默认生成在build，自行配置
        "-j=16",
        "--all-scopes-completion",
        "--completion-style=detailed",
        "--header-insertion=iwyu",
        "--pch-storage=memory",
        "--cross-file-rename",
        "--enable-config",
        "--fallback-style=WebKit",
        "--pretty",
        "--clang-tidy",
        // 网上别人配置clang++，但我这边windows、linux实测不加这行也没啥问题，可能mac可能需要另外加
        "--query-driver=clang++",
    ],
    "mlir.server_path": "/usr/local/bin/mlir-lsp-server",
    "mlir.pdll_server_path": "/usr/local/bin/mlir-pdll-lsp-server",
    "mlir.tablegen_compilation_databases": [
        "${workspaceFolder}/build/tablegen_compile_commands.yml"
    ],
}

```

Im on WSL

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.100.2",
  "cmtVersion": "1.20.53",
  "configurations": [
    {
      "folder": "/mnt/d/projs/Trycompiler/TBC",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
ain] 正在启动新的 CMake 驱动程序
[main] 正在启动 CMake 驱动程序
[cmakefileapi-driver] 正在创建 CMakeFileApiDriver 的实例
[driver] 正在使用工具包初始化基本驱动程序
[kit] 正在测试 GCC 二进制文件: /usr/bin/gcc
[proc] 执行命令: /usr/bin/gcc -v
[kit] 检测到 GCC 编译器: /usr/bin/gcc
[driver] CMakeDriver 工具包设置为 GCC 11.4.0 x86_64-linux-gnu
[kit] 工具包 'GCC 11.4.0 x86_64-linux-gnu' 的环境: {
  "USER": "lord",
  "VSCODE_WSL_EXT_LOCATION": "/mnt/c/Users/admin/.vscode/extensions/ms-vscode-remote.remote-wsl-0.99.0",
  "SHLVL": "0",
  "HOME": "/home/lord",
  "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
  "WSL_DISTRO_NAME": "Ubuntu-22.04",
  "WAYLAND_DISPLAY": "wayland-0",
  "LOGNAME": "lord",
  "NAME": "DESKTOP-0J8IJVB",
  "WSL_INTEROP": "/run/WSL/33589_interop",
  "PULSE_SERVER": "unix:/mnt/wslg/PulseServer",
  "_": "/home/lord/.vscode-server/bin/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/node",
  "TERM": "xterm-256color",
  "PATH": "/home/lord/.vscode-server/bin/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/bin/remote-cli:/home/lord/.local/bin:/home/lord/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0:/mnt/c/windows/system32/openssh:/mnt/c/program files/git/cmd:/mnt/c/program files/nvidia corporation/nvidia app/nvdlisr:/mnt/c/program files/dotnet:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Users/admin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/admin/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/admin/.cache/lm-studio/bin:/snap/bin:/usr/local/cuda-12.8/bin:/home/lord/miniconda3/bin",
  "XDG_RUNTIME_DIR": "/run/user/1000/",
  "DISPLAY": ":0",
  "LANG": "C.UTF-8",
  "SHELL": "/bin/bash",
  "PWD": "/mnt/c/Users/admin/AppData/Local/Programs/Microsoft VS Code",
  "WSL2_GUI_APPS_ENABLED": "1",
  "HOSTTYPE": "x86_64",
  "WSLENV": "VSCODE_WSL_EXT_LOCATION/up",
  "VSCODE_CWD": "/mnt/c/Users/admin/AppData/Local/Programs/Microsoft VS Code",
  "VSCODE_NLS_CONFIG": "{\"userLocale\":\"zh-cn\",\"osLocale\":\"zh-cn\",\"resolvedLanguage\":\"en\",\"defaultMessagesFile\":\"/home/lord/.vscode-server/bin/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/out/nls.messages.json\",\"locale\":\"zh-cn\",\"availableLanguages\":{}}",
  "VSCODE_HANDLES_SIGPIPE": "true",
  "CONDA_EXE": "/home/lord/miniconda3/bin/conda",
  "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
  "LESSCLOSE": "/usr/bin/lesspipe %s %s",
  "LESSOPEN": "| /usr/bin/lesspipe %s",
  "CONDA_SHLVL": "0",
  "CONDA_PYTHON_EXE": "/home/lord/miniconda3/bin/python",
  "LD_LIBRARY_PATH": "/usr/local/cuda-12.8/lib64:",
  "XDG_DATA_DIRS": "/usr/local/share:/usr/share:/var/lib/snapd/desktop",
  "CPATH": "/usr/local/cuda-12.8/targets/x86_64-linux/include:",
  "VSCODE_ESM_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "ELECTRON_RUN_AS_NODE": "1",
  "VSCODE_IPC_HOOK_CLI": "/run/user/1000/vscode-ipc-678467e3-d429-4ec0-afb4-1de9dc0ece6b.sock",
  "VSCODE_DOTNET_INSTALL_TOOL_ORIGINAL_HOME": "/home/lord",
  "VSCODE_L10N_BUNDLE_LOCATION": "vscode-local:/c%3A/Users/admin/.vscode/extensions/ms-ceintl.vscode-language-pack-zh-hans-1.100.2025051409/translations/extensions/vscode.markdown-language-features.i18n.json",
  "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true"
}
[driver] 正在尝试检测系统支持的生成器
[expand] 已展开 ${workspaceFolder}/build
[cache] 正在读取 CMake 缓存文件 /mnt/d/projs/Trycompiler/TBC/build/CMakeCache.txt
[cache] 正在分析 CMake 缓存字符串
[cache] 正在读取 CMake 缓存文件 /mnt/d/projs/Trycompiler/TBC/build/CMakeCache.txt
[cache] 正在分析 CMake 缓存字符串
[cmakefileapi-parser] Read reply folder: /mnt/d/projs/Trycompiler/TBC/build/.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-5c415109988f95a202b2.json","cmakeFiles-v1-942c19afc7a436c74894.json","codemodel-v2-0e299d8afeb52beed95f.json","directory-.-Debug-f5ebdc15457944623624.json","directory-3rdparty-Debug-a231e31bb58b23e3c223.json","directory-3rdparty.cnpy-Debug-af5edb850e16db14ff83.json","directory-include-Debug-7ead17b99bffc88b66bb.json","directory-include.conversions-Debug-d9ee85ce7422749f8fc7.json","directory-include.dialects-Debug-9cb0e511dbf37d360f26.json","directory-include.dialects.hals-Debug-4fa83da910006bb95fce.json","directory-include.dialects.kernels-Debug-a507ffdd363447de1a32.json","directory-include.dialects.operators-Debug-97a4c4b321bb3032b516.json","directory-include.dialects.operators.IR-Debug-52fbd34ea27529f0bcea.json","directory-include.dialects.operators.transforms-Debug-39e5069e1d3c82d27984.json","directory-include.interfaces-Debug-adadd3806cebed089691.json","directory-include.support-Debug-5dcddb67c27709a8da92.json","directory-include.traits-Debug-73308e87be33631f8672.json","directory-lib-Debug-5acaa9a8b4635c673300.json","directory-lib.conversions-Debug-4634eefc8dc302c00229.json","directory-lib.dialects-Debug-8e66e9d730a59fdb9616.json","directory-lib.dialects.hals-Debug-142c2cb5ee8900c3b027.json","directory-lib.dialects.kernels-Debug-61af44ed455da0e28178.json","directory-lib.dialects.operators-Debug-5ab8dd093aef318e6c88.json","directory-lib.interfaces-Debug-1862990ce2e550d6afd2.json","directory-lib.support-Debug-057f932eb392ed1ddfc4.json","directory-lib.traits-Debug-acd380108f70d7d00955.json","directory-python-Debug-8db83237229819026e8d.json","directory-tools-Debug-f9645b0170a45a75eff2.json","directory-tools.tbc-opt-Debug-a84a8ba7b347f3790b46.json","index-2025-06-03T15-58-29-0599.json","target-AArch64TargetParserTableGen-Debug-10fb90dbffcc7ea8db79.json","target-ARMTargetParserTableGen-Debug-165c26c10b29f88572d6.json","target-MLIROperatorDialectAttrGen-Debug-cf5ebcbd920d4524904c.json","target-MLIROperatorDialectPassIncGen-Debug-38cd742ea130eda7a2fa.json","target-MLIROperatorsIncGen-Debug-ff8fd588e3ba37e3ee62.json","target-MLIRShapeInferInterface-Debug-7995d76aad16c08a6dcd.json","target-MLIRShapeInferInterfaceIncGen-Debug-e1b3bf98fa6ff07d571e.json","target-MLIRTBCSupport-Debug-76e20391947214d98f3a.json","target-RISCVTargetParserTableGen-Debug-b058bbf927622d8daa12.json","target-TBCInitAll-Debug-f84c7b08419d0e4d8cdd.json","target-TBCOperators-Debug-0bf0ec620a16594d23d3.json","target-UtilsAttrGen-Debug-2bd889ae47f9079e5114.json","target-acc_gen-Debug-87131b25af37b13621bd.json","target-cnpy-Debug-f7efe69c73565c29855e.json","target-install-MLIRShapeInferInterface-Debug-296d7daf3c0f754d9cda.json","target-install-MLIRShapeInferInterface-stripped-Debug-9fc5ba329772a5beb2f9.json","target-install-MLIRTBCSupport-Debug-86af60a5fc68340de9bb.json","target-install-MLIRTBCSupport-stripped-Debug-614ad683104053d1a7ec.json","target-install-TBCInitAll-Debug-6b96ef4e5a46f458e543.json","target-install-TBCInitAll-stripped-Debug-29e2ae3b75f1273256c0.json","target-install-TBCOperators-Debug-dd1091fba8a0d34151c0.json","target-install-TBCOperators-stripped-Debug-8ecfce2d093c07497a04.json","target-install-cnpy-Debug-a4c6587f42b74301ad09.json","target-install-cnpy-stripped-Debug-96bab5d1dbcaacb48684.json","target-intrinsics_gen-Debug-e804f479ceb0a1b8ad06.json","target-mlir-doc-Debug-e48c5ec112d04520a0ac.json","target-mlir-generic-headers-Debug-37ad7dc66ca373dd9490.json","target-mlir-headers-Debug-9af6f63e9138be55e1b1.json","target-mlir-tablegen-targets-Debug-c5c2f9b7cb8da57b5204.json","target-obj.MLIRShapeInferInterface-Debug-0066af51f6ff0983a6fc.json","target-obj.TBCInitAll-Debug-75c0d2b2006931627216.json","target-obj.TBCOperators-Debug-1e25f53bc2ec12515125.json","target-omp_gen-Debug-3b3f70a7c2863b26c5a7.json","target-tbc-opt-Debug-9a6e799066429709d226.json","toolchains-v1-b754436fa6b53bbfa8e0.json"]
[rollbar] 未处理的异常: 未处理的拒绝承诺: build TypeError: Cannot read properties of undefined (reading 'major') {}
```

### Additional Information

when i try to reset cmake tools state the issue still here

**Comment by lordrebel** [comment]
its strange when i `rm -rf build/*`  then click `build` ,it works normally

**Comment by Amy-Li03** [comment]
Hi @lordrebel, we are very happy that your issue was resolved.

When using CMake, if some configuration (such as the contents of CMakeLists.txt) changes and you don't clear build, CMake may reuse the old cache, causing strange errors or build failures. Remove all the old build files in build folder can make CMake regenerate the project from a clean state.

**Comment by lordrebel** [comment]
> Hi [@lordrebel](https://github.com/lordrebel), we are very happy that your issue was resolved.
> 
> When using CMake, if some configuration (such as the contents of CMakeLists.txt) changes and you don't clear build, CMake may reuse the old cache, causing strange errors or build failures. Remove all the old build files in build folder can make CMake regenerate the project from a clean state.

but I dont konw why I click “delete cache and reconfigure”  the issue still there until I remove the build directory manually

**Comment by Amy-Li03** [comment]
When you click “Delete Cache and Reconfigure”, CMake Tools usually just deletes: CMakeCache.txt, possibly CMakeFiles folder and maybe a few other files; But when you do: `rm -rf build/*`, you are removing everything, this will allow CMake to restart the build from a completely clean state.

**Comment by lordrebel** [comment]
> When you click “Delete Cache and Reconfigure”, CMake Tools usually just deletes: CMakeCache.txt, possibly CMakeFiles folder and maybe a few other files; But when you do: `rm -rf build/*`, you are removing everything, this will allow CMake to restart the build from a completely clean state.

ok，should vscode-cmake-tools provide a feature to delete all build things then configure to avoid this issue?

**Comment by Amy-Li03** [comment]
> > When you click “Delete Cache and Reconfigure”, CMake Tools usually just deletes: CMakeCache.txt, possibly CMakeFiles folder and maybe a few other files; But when you do: `rm -rf build/*`, you are removing everything, this will allow CMake to restart the build from a completely clean state.
> 
> ok，should vscode-cmake-tools provide a feature to delete all build things then configure to avoid this issue?

You can create a new feature request to track it.

**Comment by lordrebel** [comment]
> > > When you click “Delete Cache and Reconfigure”, CMake Tools usually just deletes: CMakeCache.txt, possibly CMakeFiles folder and maybe a few other files; But when you do: `rm -rf build/*`, you are removing everything, this will allow CMake to restart the build from a completely clean state.
> > 
> > 
> > ok，should vscode-cmake-tools provide a feature to delete all build things then configure to avoid this issue?
> 
> You can create a new feature request to track it.

alright
