### ISSUE TITLE
CMake pane stays empty even after clean-reconfigure

### ISSUE THREAD

**Issue by dillonKneeland** [microsoft/vscode-cmake-tools#516]
### Brief Issue Summary

Everything works correctly but nothing is showing up in the CMake pane of the editor.

### Expected:

1. Hit configure button
2. CMake pane populates with CMake configuration data and projects.

### Apparent Behavior:

1. Hit configure button
2. Projects configures
3. Nothing displays in CMake pane.

### CMake Tools Log

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/users/evac/documents/projects/boltengine -Bc:/users/evac/documents/projects/boltengine/build
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Deprecation Warning at source/contrib/glfw/CMakeLists.txt:10 (cmake_policy):
[cmake]   The OLD behavior for policy CMP0042 will be removed from a future version
[cmake]   of CMake.
[cmake] 
[cmake]   The cmake-policies(7) manual explains that the OLD behaviors of all
[cmake]   policies are deprecated and that a policy should be set to OLD only under
[cmake]   specific short-term circumstances.  Projects should be ported to the NEW
[cmake]   behavior and not rely on setting a policy to OLD.
[cmake] 
[cmake] 
[cmake] -- Could NOT find Vulkan (missing: VULKAN_LIBRARY) 
[cmake] -- Using Win32 for window creation
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/evac/Documents/Projects/BoltEngine/build
```

### Developer Tools Log

```
log.ts:159  INFO no standard startup: panel is active
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.119Z [debug] [rollbar] Updated Rollbar payload {"environment":"production","packageJSON":{"name":"cmake-tools","version":"1.1.1"},"client":{"code_version":"1.1.1"},"platform":"win32"} (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] activating extension (at Object.activate (C:\Users\evac\.vscode-insiders\extensions\ms-vscode.cpptools-0.18.0\out\src\LanguageServer\extension.js:26:13))
console.ts:136 [Extension Host] starting language server (at realActivation (C:\Users\evac\.vscode-insiders\extensions\ms-vscode.cpptools-0.18.0\out\src\LanguageServer\extension.js:78:13))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.162Z [debug] [kit] Reading kits file C:\Users\evac\AppData\Roaming\CMakeTools\cmake-tools.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.163Z [debug] [kit] Not reading non-existent kits file: c:\Users\evac\Documents\Projects\BoltEngine\.vscode\cmake-kits.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.243Z [info] [kit] Successfully loaded 2 kits from C:\Users\evac\AppData\Roaming\CMakeTools\cmake-tools.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.244Z [debug] [main] Safe constructing new CMakeTools instance (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.245Z [debug] [variant] Constructing VariantManager (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.246Z [debug] [main] Constructing new CMakeTools instance (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.246Z [debug] [main] Starting CMakeTools second-phase init (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.247Z [debug] [rollbar] Checking Rollbar permissions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.247Z [debug] [rollbar] Rollbar enabled?  false (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.309Z [info] [variant] Loaded new set of variants (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.318Z [debug] [main] CMakeTools instance initialization complete. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.318Z [debug] [main] Injecting new Kit into CMake driver (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.325Z [debug] [kit] Reading kits file C:\Users\evac\AppData\Roaming\CMakeTools\cmake-tools.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.345Z [info] [kit] Successfully loaded 2 kits from C:\Users\evac\AppData\Roaming\CMakeTools\cmake-tools.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.347Z [debug] [kit] Not reading non-existent kits file: c:\Users\evac\Documents\Projects\BoltEngine\.vscode\cmake-kits.json (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.349Z [debug] [rollbar] Updated Rollbar payload {"kit":{"name":"Visual Studio Community 2017 - amd64","visualStudio":"c078fe70","visualStudioArchitecture":"amd64","preferredGenerator":{"name":"Visual Studio 15 2017","platform":"x64"}}} (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.350Z [debug] [main] Injecting new Kit into CMake driver (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.354Z [debug] [extension] Configuring workspace on open  file:///c%3A/Users/evac/Documents/Projects/BoltEngine (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.354Z [debug] [main] Run configure   (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.355Z [debug] [main] Saving open files before configure/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.419Z [debug] [main] Starting new CMake driver (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.420Z [debug] [main] Starting CMake driver (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.420Z [debug] [legacy-driver] Creating instance of LegacyCMakeDriver (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:10.422Z [debug] [driver] CMakeDriver Kit set to Visual Studio Community 2017 - amd64 (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.445Z [debug] [driver] Run _refreshExpansions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.446Z [debug] [driver] Run _refreshExpansions cb (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.447Z [debug] [cache] Reading CMake cache file c:/users/evac/documents/projects/boltengine/build/cmakecache.txt (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.449Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.463Z [debug] [driver] Setting new variant , Emit debug information without performing optimizations (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.463Z [debug] [driver] Run _refreshExpansions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.464Z [debug] [driver] Run _refreshExpansions cb (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.490Z [debug] [driver] Start configure   (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.490Z [debug] [driver] Runnnig pre-configure checks and steps (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.494Z [debug] [driver] Run _refreshExpansions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.494Z [debug] [driver] Run _refreshExpansions cb (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.495Z [debug] [legacy-driver] Invoking CMake C:\Program Files\CMake\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-Hc:/users/evac/documents/projects/boltengine","-Bc:/users/evac/documents/projects/boltengine/build"] (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.498Z [info] [proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/users/evac/documents/projects/boltengine -Bc:/users/evac/documents/projects/boltengine/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.511Z [info] [cmake] Not searching for unused variables given on the command line. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.545Z [error] [cmake] CMake Deprecation Warning at source/contrib/glfw/CMakeLists.txt:10 (cmake_policy): (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.545Z [error] [cmake]   The OLD behavior for policy CMP0042 will be removed from a future version (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.546Z [error] [cmake]   of CMake. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.546Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.546Z [error] [cmake]   The cmake-policies(7) manual explains that the OLD behaviors of all (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.546Z [error] [cmake]   policies are deprecated and that a policy should be set to OLD only under (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.547Z [error] [cmake]   specific short-term circumstances.  Projects should be ported to the NEW (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.547Z [error] [cmake]   behavior and not rely on setting a policy to OLD. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.547Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.548Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.581Z [info] [cmake] -- Could NOT find Vulkan (missing: VULKAN_LIBRARY)  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.582Z [info] [cmake] -- Using Win32 for window creation (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.590Z [info] [cmake] -- Configuring done (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.629Z [info] [cmake] -- Generating done (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.631Z [info] [cmake] -- Build files have been written to: C:/Users/evac/Documents/Projects/BoltEngine/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.636Z [debug] [cache] Reading CMake cache file c:/users/evac/documents/projects/boltengine/build/cmakecache.txt (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:11.637Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.687Z [debug] [extension] [6964] cmake.build started (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.688Z [debug] [main] Run build  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.708Z [debug] [main] Saving open files before configure/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.748Z [info] [build] Starting build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.759Z [debug] [driver] Start build ALL_BUILD (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.759Z [debug] [driver] Runnnig pre-configure checks and steps (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.762Z [info] [proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/users/evac/documents/projects/boltengine/build --config Debug --target ALL_BUILD -- /m /property:GenerateFullPaths=true (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.845Z [info] [build] Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Framework (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.845Z [info] [build] Copyright (C) Microsoft Corporation. All rights reserved. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:33.845Z [info] [build]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.044Z [info] [build] Build started 8/17/2018 2:28:34 PM. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.764Z [info] [build]      1>Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" on node 1 (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.765Z [info] [build]      1>Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\evac\Documents\Projects\BoltEngine\build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.766Z [info] [build]      2>InitializeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.766Z [info] [build]          Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.815Z [info] [build]        CustomBuild: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.816Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.830Z [info] [build]        FinalizeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.831Z [info] [build]          Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.835Z [info] [build]          Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:34.847Z [info] [build]      2>Done Building Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ZERO_CHECK.vcxproj" (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.645Z [info] [build]      1>Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\evac\Documents\Projects\BoltEngine\build\source\contrib\glfw\src\glfw.vcxproj" (5) on node 4 (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.646Z [info] [build]      5>InitializeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.646Z [info] [build]          Creating "glfw.dir\Debug\glfw.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.695Z [info] [build]        CustomBuild: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.696Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.760Z [info] [build]        ClCompile: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.760Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.782Z [info] [build]        Lib: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.782Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.784Z [info] [build]          glfw.vcxproj -> C:\Users\evac\Documents\Projects\BoltEngine\build\lib\Debug\glfw3.lib (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.795Z [info] [build]        FinalizeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.796Z [info] [build]          Deleting file "glfw.dir\Debug\glfw.tlog\unsuccessfulbuild". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.797Z [info] [build]          Touching "glfw.dir\Debug\glfw.tlog\glfw.lastbuildstate". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.799Z [info] [build]      5>Done Building Project "C:\Users\evac\Documents\Projects\BoltEngine\build\source\contrib\glfw\src\glfw.vcxproj" (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.814Z [info] [build]      1>Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\evac\Documents\Projects\BoltEngine\build\source\bolt-core\bolt_core.vcxproj" (4) on node 3 (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.815Z [info] [build]      4>InitializeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.815Z [info] [build]          Creating "bolt_core.dir\Debug\bolt_core.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.821Z [info] [build]        CustomBuild: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.822Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.830Z [info] [build]        ClCompile: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.830Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.838Z [info] [build]        Lib: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.838Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.840Z [info] [build]          bolt_core.vcxproj -> C:\Users\evac\Documents\Projects\BoltEngine\build\lib\Debug\bolt_core.lib (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.845Z [info] [build]        FinalizeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.845Z [info] [build]          Deleting file "bolt_core.dir\Debug\bolt_core.tlog\unsuccessfulbuild". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.846Z [info] [build]          Touching "bolt_core.dir\Debug\bolt_core.tlog\bolt_core.lastbuildstate". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.846Z [info] [build]      4>Done Building Project "C:\Users\evac\Documents\Projects\BoltEngine\build\source\bolt-core\bolt_core.vcxproj" (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.861Z [info] [build]      1>Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" (1) is building "C:\Users\evac\Documents\Projects\BoltEngine\build\source\BoltEngine.vcxproj" (3) on node 2 (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.861Z [info] [build]      3>InitializeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.862Z [info] [build]          Creating "BoltEngine.dir\Debug\BoltEngine.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.888Z [info] [build]        CustomBuild: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.888Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.899Z [info] [build]        ClCompile: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.899Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.928Z [info] [build]        Link: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.928Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.929Z [info] [build]          BoltEngine.vcxproj -> C:\Users\evac\Documents\Projects\BoltEngine\build\bin\Debug\BoltEngine.exe (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.932Z [info] [build]        FinalizeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.932Z [info] [build]          Deleting file "BoltEngine.dir\Debug\BoltEngine.tlog\unsuccessfulbuild". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.932Z [info] [build]          Touching "BoltEngine.dir\Debug\BoltEngine.tlog\BoltEngine.lastbuildstate". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.933Z [info] [build]      3>Done Building Project "C:\Users\evac\Documents\Projects\BoltEngine\build\source\BoltEngine.vcxproj" (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.942Z [info] [build]      1>InitializeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.942Z [info] [build]          Creating "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.944Z [info] [build]        CustomBuild: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.944Z [info] [build]          All outputs are up-to-date. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.945Z [info] [build]        FinalizeBuildStatus: (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.946Z [info] [build]          Deleting file "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.947Z [info] [build]          Touching "Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate". (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.947Z [info] [build]      1>Done Building Project "C:\Users\evac\Documents\Projects\BoltEngine\build\ALL_BUILD.vcxproj" (default targets). (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.969Z [info] [build]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.970Z [info] [build] Build succeeded. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.970Z [info] [build]     0 Warning(s) (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.971Z [info] [build]     0 Error(s) (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.971Z [info] [build]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.971Z [info] [build] Time Elapsed 00:00:01.92 (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.992Z [debug] [cache] Reading CMake cache file c:/users/evac/documents/projects/boltengine/build/cmakecache.txt (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:35.993Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:36.008Z [debug] [driver] Run _refreshExpansions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:36.008Z [debug] [driver] Run _refreshExpansions cb (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:36.009Z [info] [build] Build finished with exit code 0 (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:28:36.012Z [debug] [extension] [6964] cmake.build finished (returned 0) (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.545Z [debug] [extension] [3517] cmake.configure started (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.545Z [debug] [main] Run configure   (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.546Z [debug] [main] Saving open files before configure/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.598Z [debug] [driver] Start configure   (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.598Z [debug] [driver] Runnnig pre-configure checks and steps (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.601Z [debug] [driver] Run _refreshExpansions (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.601Z [debug] [driver] Run _refreshExpansions cb (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.602Z [debug] [legacy-driver] Invoking CMake C:\Program Files\CMake\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-Hc:/users/evac/documents/projects/boltengine","-Bc:/users/evac/documents/projects/boltengine/build"] (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.605Z [info] [proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/users/evac/documents/projects/boltengine -Bc:/users/evac/documents/projects/boltengine/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.617Z [info] [cmake] Not searching for unused variables given on the command line. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.644Z [error] [cmake] CMake Deprecation Warning at source/contrib/glfw/CMakeLists.txt:10 (cmake_policy): (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.644Z [error] [cmake]   The OLD behavior for policy CMP0042 will be removed from a future version (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.645Z [error] [cmake]   of CMake. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.645Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.646Z [error] [cmake]   The cmake-policies(7) manual explains that the OLD behaviors of all (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.646Z [error] [cmake]   policies are deprecated and that a policy should be set to OLD only under (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.646Z [error] [cmake]   specific short-term circumstances.  Projects should be ported to the NEW (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.647Z [error] [cmake]   behavior and not rely on setting a policy to OLD. (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.647Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.648Z [error] [cmake]  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:152:25))
t.log @ console.ts:136
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.683Z [info] [cmake] -- Could NOT find Vulkan (missing: VULKAN_LIBRARY)  (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.683Z [info] [cmake] -- Using Win32 for window creation (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.691Z [info] [cmake] -- Configuring done (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.728Z [info] [cmake] -- Generating done (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.732Z [info] [cmake] -- Build files have been written to: C:/Users/evac/Documents/Projects/BoltEngine/build (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.737Z [debug] [cache] Reading CMake cache file c:/users/evac/documents/projects/boltengine/build/cmakecache.txt (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.738Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
console.ts:136 [Extension Host] [CMakeTools] 2018-08-17T18:32:04.772Z [debug] [extension] [3517] cmake.configure finished (returned 0) (at SingletonLogger._log (C:\Users\evac\.vscode-insiders\extensions\vector-of-bool.cmake-tools-1.1.1\out\src\logging.js:142:29))
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.12.1
- **VSCode Version**: 1.27.0-insider
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: Visual C++ 2017 Community

### Other Notes/Information

The tool is super handy and this is mostly just a minor inconvenience that I thought I should alert you to. Thanks.

**Comment by vector-of-bool** [comment]
Sorry for the delay. Does this still occur in VSCode 1.27.2+? This _may_ be an upstream bug.

**Comment by john-mullins** [comment]
I have this issue with a particular CMakeLists.txt file and project, all of my others work fine. The issue occurs on both Windows and Linux. Some of the files are proprietary but I could probably provide the folder structure with some empty files to demonstrate the issue. I am using VSCode 1.27.2.

**Comment by ShechemKS** [comment]
Same issue here, 
Ubuntu 16.04
CMake version: 0.0.17
CMake Tools version: 1.1.3
VSCode Version: 1.35.1

**Comment by john-mullins** [comment]
It seems to be a problem with cmake version 3.12. It also only occurs with some of my projects.

I fixed this issue by upgrading my version of CMake to 3.13.

**Comment by ShechemKS** [comment]
I currently have CMake version 3.5.1, yet the issue persists.

**Comment by ShechemKS** [comment]
Fixed. Thanks

**Comment by bobbrow** [comment]
If this is still an issue, please let us know.  We will close it for now.
